version: '3.41.0'

includes:
  installTasks: ./tasks/InstallTasks.yml
  deployTasks: ./tasks/DeployTasks.yml

set: [pipefail]
shopt: [globstar]

dotenv:
  - '.env'

tasks:
  create-cluster:
    aliases:
      - create
    deps:
      - installTasks:k3d
      - installTasks:orbstack
      - installTasks:kubectl
      - installTasks:kubescape
    cmds:
      - k3d cluster create $CLUSTER_NAME --config configs/k3d_config_$CLUSTER_NAME.yaml
      - echo $KUBECONFIG
      - kubectl get nodes
    requires:
      vars:
        - CLUSTER_NAME
    status:
      - k3d cluster list $CLUSTER_NAME
    preconditions:
      - test -d configs
      - test -f configs/k3d_config_$CLUSTER_NAME.yaml

  delete-cluster:
    aliases:
      - delete
    prompt: You're about to delete the '{{.CLUSTER_NAME}}' k3d cluster... Do you want to continue?
    cmds:
      - k3d cluster delete $CLUSTER_NAME
    requires:
      vars:
        - CLUSTER_NAME

  delete-all-clusters:
    aliases:
      - delete-all
    prompt: You're about to delete all of your k3d clusters... Do you want to continue?
    cmds:
      - k3d cluster delete --all
    requires:
      vars:
        - CLUSTER_NAME