version: '3.41.0'

includes:
  deployTasks: ./DeployTasks.yml

tasks:
  deploy_all_providers:
    deps:
      - :create-cluster
      - installTasks:kubectl
      - deployTasks:crossplane
    cmds:
      - kubectl apply -f configs/crossplane/*.yaml
    preconditions:
      - test -d configs/crossplane

  deploy_s3_provider:
    aliases:
      - s3_provider
    deps:
      - :create-cluster
      - installTasks:kubectl
      - deployTasks:crossplane
    cmds:
      - kubectl apply -f configs/crossplane/aws-s3.yaml
    preconditions:
      - test -d configs/crossplane
      - test -f configs/crossplane/aws-s3.yaml