version: '3.41.0'

includes:
  installTasks: ./InstallTasks.yml

tasks:
  apply_all_manifests:
    aliases:
      - all_manifests
    cmds:
      - kubectl apply -f manifests/*
    requires:
      vars:
        - CLUSTER_NAME
    preconditions:
      - test -d manifests
      - k3d cluster list $CLUSTER_NAME

  add_argo_helm_repo:
    internal: true
    aliases:
      - argo_helm
    deps:
      - installTasks:helm
    cmds:
      - helm repo add argo https://argoproj.github.io/argo-helm
    status:
      - helm repo list | grep -i argo

  argo_workflows:
    aliases:
      - workflows
    deps:
      - installTasks:helm
      - add_argo_helm_repo
    cmds:
      - helm upgrade -i $ARGO_WORKFLOWS_RELEASE_NAME argo/argo-workflows
    requires:
      vars:
        - ARGO_WORKFLOWS_RELEASE_NAME
    preconditions:
      - test -d values
      - test -f values/argo-workflows-values.yaml